### ISSUE TITLE
Error notification

### ISSUE THREAD

**Issue by Carlini0** [mass-immersion-approach/MIA-Japanese-Add-on#81]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: macOS Big Sur 11.2.2

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
[ Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-04-21 12:26:59
Add-ons possibly involved: ⁨Migaku Japanese⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 53, in handler
  File "aqt/main.py", line 142, in on_window_init
  File "aqt/main.py", line 231, in setupProfile
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-12>", line 2, in loadProfile
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 633, in repl
  File "aqt/main.py", line 427, in loadProfile
  File "aqt/gui_hooks.py", line 2033, in __call__
  File "anki/hooks.py", line 583, in runHook
  File "/Users/Ben/Library/Application Support/Anki2/addons21/278530045/autoCSSJSHandling.py", line 92, in injectWrapperElements
    self.mw.col.models.save(model)
  File "anki/models.py", line 87, in save
  File "anki/models.py", line 231, in update
  File "anki/rsbackend_gen.py", line 414, in add_or_update_notetype
  File "anki/rsbackend.py", line 267, in _run_command
anki.rsbackend.TemplateError: Card template ⁨1⁩ has a problem. ]

**Comment by KieranBrannigan** [comment]
What were you doing when this error showed up? Are you able to replicate the problem?

**Comment by Carlini0** [comment]
Restarting Anki. I don’t have any Migaku cards yet.

Yes.
